#!/bin/bash
################################################################################
# Home Assistant Auto-Update Script
#
# Description: Automatically pulls latest changes from GitHub and safely
#              applies them with backup and validation
#
# Features:
# - Automatic backup before update
# - YAML validation before restart
# - Auto-rollback on errors
# - Notifications on success/failure
# - Detailed logging
#
# Schedule: Daily at 03:00 AM (via cron)
# Branch: arbeit-updates
#
# Author: Generated by Claude Code
# Date: 2025-10-28
################################################################################

set -euo pipefail  # Exit on error, undefined vars, pipe failures

# ============================================================================
# CONFIGURATION
# ============================================================================

# Paths
CONFIG_DIR="/config"
REPO_DIR="/config"
BACKUP_DIR="/config/backups/auto"
LOG_DIR="/config/logs"
LOG_FILE="${LOG_DIR}/auto_update.log"

# Git settings
BRANCH="arbeit-updates"
REMOTE="origin"

# Home Assistant
HA_CLI="ha"
HA_CHECK_CMD="ha core check"
HA_RESTART_CMD="ha core restart"

# Notifications
NOTIFY_SERVICE="notify.alexa_media_wohnzimmer"

# Backup retention
BACKUP_RETENTION_DAYS=7

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

# Logging function
log() {
    local level=$1
    shift
    local message="$@"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[${timestamp}] [${level}] ${message}" | tee -a "${LOG_FILE}"
}

# Create notification via Home Assistant REST API
send_notification() {
    local title="$1"
    local message="$2"
    local level="${3:-info}"  # info, warning, error

    log "INFO" "Sending notification: ${title}"

    # Use Home Assistant REST API to send notification
    curl -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
        -d "{\"title\":\"${title}\",\"message\":\"${message}\"}" \
        "http://supervisor/core/api/services/notify/alexa_media_wohnzimmer" \
        2>/dev/null || log "WARN" "Failed to send notification"
}

# Create timestamped backup
create_backup() {
    local timestamp=$(date '+%Y-%m-%d_%H-%M-%S')
    local backup_file="${BACKUP_DIR}/config_backup_${timestamp}.tar.gz"

    log "INFO" "Creating backup: ${backup_file}"

    # Create backup directory if not exists
    mkdir -p "${BACKUP_DIR}"

    # Create tar.gz backup (exclude large files)
    tar -czf "${backup_file}" \
        -C "${CONFIG_DIR}" \
        --exclude='*.db' \
        --exclude='*.db-shm' \
        --exclude='*.db-wal' \
        --exclude='backups' \
        --exclude='deps' \
        --exclude='.storage' \
        --exclude='tts' \
        --exclude='logs' \
        . 2>&1 | tee -a "${LOG_FILE}"

    if [ $? -eq 0 ]; then
        log "INFO" "Backup created successfully: ${backup_file}"
        echo "${backup_file}"
        return 0
    else
        log "ERROR" "Backup creation failed!"
        return 1
    fi
}

# Restore from backup
restore_backup() {
    local backup_file="$1"

    log "WARN" "Restoring from backup: ${backup_file}"

    if [ ! -f "${backup_file}" ]; then
        log "ERROR" "Backup file not found: ${backup_file}"
        return 1
    fi

    # Extract backup
    tar -xzf "${backup_file}" -C "${CONFIG_DIR}" 2>&1 | tee -a "${LOG_FILE}"

    if [ $? -eq 0 ]; then
        log "INFO" "Backup restored successfully"
        return 0
    else
        log "ERROR" "Backup restore failed!"
        return 1
    fi
}

# Clean old backups
cleanup_old_backups() {
    log "INFO" "Cleaning backups older than ${BACKUP_RETENTION_DAYS} days"

    find "${BACKUP_DIR}" -name "config_backup_*.tar.gz" -type f -mtime +${BACKUP_RETENTION_DAYS} -delete

    local remaining=$(find "${BACKUP_DIR}" -name "config_backup_*.tar.gz" -type f | wc -l)
    log "INFO" "Remaining backups: ${remaining}"
}

# Check if there are updates available
check_for_updates() {
    log "INFO" "Checking for updates on ${REMOTE}/${BRANCH}"

    cd "${REPO_DIR}"

    # Fetch latest changes
    git fetch "${REMOTE}" "${BRANCH}" 2>&1 | tee -a "${LOG_FILE}"

    # Compare local and remote
    local local_commit=$(git rev-parse HEAD)
    local remote_commit=$(git rev-parse "${REMOTE}/${BRANCH}")

    log "INFO" "Local commit:  ${local_commit}"
    log "INFO" "Remote commit: ${remote_commit}"

    if [ "${local_commit}" = "${remote_commit}" ]; then
        log "INFO" "Already up to date. No updates needed."
        return 1  # No updates
    else
        log "INFO" "Updates available!"
        return 0  # Updates available
    fi
}

# Pull latest changes
pull_changes() {
    log "INFO" "Pulling changes from ${REMOTE}/${BRANCH}"

    cd "${REPO_DIR}"

    # Check for local changes (stash if needed)
    if ! git diff-index --quiet HEAD --; then
        log "WARN" "Local changes detected. Stashing..."
        git stash save "Auto-stash before update $(date)" 2>&1 | tee -a "${LOG_FILE}"
    fi

    # Pull changes
    git pull "${REMOTE}" "${BRANCH}" 2>&1 | tee -a "${LOG_FILE}"
    local pull_status=$?

    if [ ${pull_status} -ne 0 ]; then
        log "ERROR" "Git pull failed with status ${pull_status}"

        # Check for merge conflicts
        if git status | grep -q "both modified"; then
            log "ERROR" "Merge conflict detected!"
            return 2  # Merge conflict
        fi

        return 1  # Other error
    fi

    log "INFO" "Git pull successful"
    return 0
}

# Validate Home Assistant configuration
validate_config() {
    log "INFO" "Validating Home Assistant configuration"

    # Run HA config check
    ${HA_CHECK_CMD} 2>&1 | tee -a "${LOG_FILE}"
    local check_status=$?

    if [ ${check_status} -eq 0 ]; then
        log "INFO" "Configuration is valid ✓"
        return 0
    else
        log "ERROR" "Configuration validation failed!"
        return 1
    fi
}

# Restart Home Assistant
restart_homeassistant() {
    log "INFO" "Restarting Home Assistant"

    ${HA_RESTART_CMD} 2>&1 | tee -a "${LOG_FILE}"

    if [ $? -eq 0 ]; then
        log "INFO" "Home Assistant restart initiated"
        return 0
    else
        log "ERROR" "Home Assistant restart failed!"
        return 1
    fi
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

main() {
    log "INFO" "=========================================="
    log "INFO" "Starting Auto-Update Process"
    log "INFO" "=========================================="

    # Ensure log directory exists
    mkdir -p "${LOG_DIR}"

    # Step 1: Check for updates
    if ! check_for_updates; then
        log "INFO" "No updates available. Exiting."
        send_notification "HA Auto-Update" "No updates available. System is up to date." "info"
        cleanup_old_backups
        return 0
    fi

    # Step 2: Create backup
    BACKUP_FILE=$(create_backup)
    if [ $? -ne 0 ]; then
        log "ERROR" "Backup creation failed. Aborting update."
        send_notification "HA Auto-Update FAILED" "Backup creation failed. Update aborted." "error"
        return 1
    fi

    # Step 3: Pull changes
    pull_changes
    local pull_status=$?

    if [ ${pull_status} -eq 2 ]; then
        # Merge conflict
        log "ERROR" "Merge conflict detected. Rolling back."
        send_notification "HA Auto-Update CONFLICT" "Merge conflict detected. Update aborted. Manual intervention required." "error"
        restore_backup "${BACKUP_FILE}"
        return 1
    elif [ ${pull_status} -ne 0 ]; then
        # Other error
        log "ERROR" "Git pull failed. Rolling back."
        send_notification "HA Auto-Update FAILED" "Git pull failed. Update aborted." "error"
        restore_backup "${BACKUP_FILE}"
        return 1
    fi

    # Step 4: Validate configuration
    if ! validate_config; then
        log "ERROR" "Configuration validation failed. Rolling back."
        send_notification "HA Auto-Update FAILED" "Invalid YAML configuration. Rolling back to previous version." "error"
        restore_backup "${BACKUP_FILE}"
        return 1
    fi

    # Step 5: Restart Home Assistant
    if ! restart_homeassistant; then
        log "ERROR" "Home Assistant restart failed."
        send_notification "HA Auto-Update WARNING" "Update successful but restart failed. Check logs." "warning"
        return 1
    fi

    # Step 6: Success!
    log "INFO" "=========================================="
    log "INFO" "Auto-Update Completed Successfully!"
    log "INFO" "=========================================="

    send_notification "HA Auto-Update SUCCESS" "Configuration updated and restarted successfully." "info"

    # Clean up old backups
    cleanup_old_backups

    return 0
}

# Execute main function
main "$@"
exit $?
