# ============================================================================
# BLIND AGENT (Radically Simplified)
# Direct control for blinds/shutters.
# ============================================================================

# ----------------------------------------------------------------------------
# HELPERS
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  # --- SUNRISE OPEN ---
  - alias: "Rollladen Wohnzimmer - Auf (Sonnenaufgang)"
    trigger:
      - platform: sun
        event: sunrise
        offset: "01:00:00"
    condition:

    action:
      - action: cover.open_cover
        target:
          entity_id: cover.wohnzimmer_wohnzimmer_rollladen_vorhang

  - alias: "Rollladen Küche - Auf (Sonnenaufgang)"
    trigger:
      - platform: sun
        event: sunrise
        offset: "01:00:00"
    condition:

    action:
      - action: cover.open_cover
        target:
          entity_id: cover.kuche_kueche_rollladen_vorhang

  - alias: "Rollladen Kiffzimmer - Auf (Sonnenaufgang)"
    trigger:
      - platform: sun
        event: sunrise
        offset: "01:00:00"
    condition:

    action:
      - action: cover.open_cover
        target:
          entity_id: cover.kiffzimmer_kiffzimmer_rollladen_vorhang

  - alias: "Rollladen Schlafzimmer - Auf (Sonnenaufgang)"
    trigger:
      - platform: sun
        event: sunrise
        offset: "01:00:00"
    condition:

    action:
      - action: cover.close_cover # Inverted
        target:
          entity_id: cover.schlafzimmer_schlafzimmer_rollladen_vorhang

  # --- SUNSET CLOSE ---
  - alias: "Rollladen Wohnzimmer - Zu (Sonnenuntergang)"
    trigger:
      - platform: sun
        event: sunset
        offset: "01:00:00"
    condition:

    action:
      - action: cover.close_cover
        target:
          entity_id: cover.wohnzimmer_wohnzimmer_rollladen_vorhang

  - alias: "Rollladen Küche - Zu (Sonnenuntergang)"
    trigger:
      - platform: sun
        event: sunset
        offset: "01:00:00"
    condition:

    action:
      - action: cover.close_cover
        target:
          entity_id: cover.kuche_kueche_rollladen_vorhang

  - alias: "Rollladen Kiffzimmer - Zu (Sonnenuntergang)"
    trigger:
      - platform: sun
        event: sunset
        offset: "01:00:00"
    condition:

    action:
      - action: cover.close_cover
        target:
          entity_id: cover.kiffzimmer_kiffzimmer_rollladen_vorhang

  - alias: "Rollladen Schlafzimmer - Zu (Sonnenuntergang)"
    trigger:
      - platform: sun
        event: sunset
        offset: "01:00:00"
    condition:

    action:
      - action: cover.open_cover # Inverted
        target:
          entity_id: cover.schlafzimmer_schlafzimmer_rollladen_vorhang

  # --- SLEEP DETECTION ---
  - alias: "Schlafzimmer - Zu bei Schlaf"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "on"
        for:
          minutes: 15
    condition:
      - condition: time
        after: "22:00:00"
        before: "08:00:00"
    action:
      - action: cover.open_cover # Inverted
        target:
          entity_id: cover.schlafzimmer_schlafzimmer_rollladen_vorhang

  # --- SUMMER PROTECTION ---
  - alias: "Sommer - Zu bei Hitze"
    trigger:
      - platform: numeric_state
        entity_id: sensor.no_area_sun_solare_elevation
        above: 50
    condition:
      - condition: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        above: 22
    action:
      - action: cover.close_cover
        target:
          entity_id:
            - cover.wohnzimmer_wohnzimmer_rollladen_vorhang
            - cover.kuche_kueche_rollladen_vorhang
            - cover.kiffzimmer_kiffzimmer_rollladen_vorhang
