# ============================================================================
# CLIMATE AGENT
# Version: 1.0.0
# Last Audit: 2026-01-28
# Centralized control for all heating, cooling, and ventilation logic.
# ============================================================================

# ----------------------------------------------------------------------------
# HELPERS (Encapsulated)
# ----------------------------------------------------------------------------
input_boolean:
  climate_agent_master:
    name: "Climate Agent Master Switch"
    icon: mdi:thermostat-auto
    initial: on

# ----------------------------------------------------------------------------
# SENSORS
# ----------------------------------------------------------------------------
template:
  - sensor:
      - name: "Climate Agent Status"
        unique_id: climate_agent_status
        state: >
          {% if is_state('input_boolean.climate_agent_master', 'on') %}
            Active
          {% else %}
            Disabled
          {% endif %}
        attributes:
          heating_mode: "{{ states('input_boolean.heizung_winter_mode') }}"
          avg_temp: >
            {{ ( (states('sensor.wohnzimmer_thermostat_computer_temperatur') | float(0)) + 
                 (states('sensor.badezimmer_thermostat_bad_temperatur') | float(0)) ) / 2 | round(1) }}

# ----------------------------------------------------------------------------
# SCRIPTS
# ----------------------------------------------------------------------------
script:
  heating_comfort_now:
    alias: "Heizung - Sofort Komfort"
    description: "Manually set heating to comfort temperature"
    mode: single
    sequence:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"

  fan_winter_heat_now:
    alias: "Ventilator - Winter Wärmeverteilung starten"
    description: "Manually start ceiling fan in winter heat distribution mode"
    mode: single
    sequence:
      - action: fan.turn_on
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          percentage: 33
          direction: "reverse"

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  - id: heating_presence_on
    alias: Heizung - Komfort bei Anwesenheit
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: home
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"
    mode: single

  - id: heating_away_eco
    alias: Heizung - Eco bei Abwesenheit
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: not_home
        for:
          minutes: 10
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: 18
    mode: single

  - id: heating_night_mode
    alias: Heizung - Nachtmodus
    trigger:
      - platform: time
        at: "22:00"
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: 17
    mode: single

  - id: heating_cold_bedroom
    alias: "Heizung - Kaltes Schlafzimmer"
    description: "Keep bedroom cooler than other rooms (max 18°C)"
    trigger:
      - platform: time
        at: "06:00:00"
      - platform: time
        at: "22:00:00"
      - platform: state
        entity_id: input_boolean.heizung_winter_mode
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
      - condition: state
        entity_id: input_boolean.heizung_winter_mode
        state: "on"
    action:
      - action: climate.set_temperature
        target:
          entity_id: climate.wohnzimmer_thermostat_computer
        data:
          temperature: 18
    mode: single

  - id: summer_ceiling_fan_auto
    alias: "Sommer - Deckenventilator bei Hitze"
    trigger:
      - platform: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        above: 24
      - platform: state
        entity_id: person.jonas_glawion
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
      - condition: state
        entity_id: person.jonas_glawion
        state: "home"
      - condition: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        above: 24
      - condition: template
        value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
    action:
      - action: fan.turn_on
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          percentage: 66
    mode: single

  - id: summer_ceiling_fan_off
    alias: "Sommer - Deckenventilator aus bei Kühle"
    trigger:
      - platform: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        below: 22
    condition:
      - condition: state
        entity_id: input_boolean.climate_agent_master
        state: "on"
      - condition: template
        value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
    action:
      - action: fan.turn_off
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
    mode: single
