# ============================================================================
# CLIMATE AGENT (Radically Simplified)
# Centralized heating and cooling.
# ============================================================================

# ----------------------------------------------------------------------------
# SENSORS
# ----------------------------------------------------------------------------
template:
  - sensor:
      - name: "Climate Agent Status"
        unique_id: climate_agent_status
        state: "Active"
        attributes:
          heating_mode: "{{ 'on' if now().month in [1, 2, 3, 4, 10, 11, 12] else 'off' }}"
          avg_temp: >
            {{ ( (states('sensor.wohnzimmer_thermostat_computer_temperatur') | float(0)) + 
                 (states('sensor.badezimmer_thermostat_bad_temperatur') | float(0)) ) / 2 | round(1) }}

# ----------------------------------------------------------------------------
# SCRIPTS
# ----------------------------------------------------------------------------
script:
  heating_comfort_now:
    alias: "Heizung - Sofort Komfort"
    mode: single
    sequence:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"

  fan_winter_heat_now:
    alias: "Ventilator - Winter Wärmeverteilung starten"
    mode: single
    sequence:
      - action: fan.turn_on
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          percentage: 33
          direction: "reverse"

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  - id: heating_presence_on
    alias: "Heizung - Komfort bei Anwesenheit"
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: home
    condition:
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"

  - id: heating_away_eco
    alias: "Heizung - Eco bei Abwesenheit"
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: not_home
        for:
          minutes: 10
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: 18

  - id: heating_night_mode
    alias: "Heizung - Nachtmodus"
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: 17

  - id: heating_morning_restore_weekday
    alias: "Heizung - Morgen Komfort Werktag (06:00)"
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
      - condition: state
        entity_id: person.jonas_glawion
        state: home
      - condition: time
        weekday: [mon, tue, wed, thu, fri]
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"

  - id: heating_morning_restore_weekend
    alias: "Heizung - Morgen Komfort Wochenende (09:00)"
    trigger:
      - platform: time
        at: "09:00:00"
    condition:
      - condition: template
        value_template: "{{ now().month in [1, 2, 3, 4, 10, 11, 12] }}"
      - condition: state
        entity_id: person.jonas_glawion
        state: home
      - condition: time
        weekday: [sat, sun]
    action:
      - action: climate.set_temperature
        target:
          entity_id:
            - climate.badezimmer_thermostat_bad
            - climate.wohnzimmer_thermostat_computer
        data:
          temperature: "{{ 23 if now().month in [11, 12, 1, 2] else 22 }}"

  - id: summer_ceiling_fan_on_temp
    alias: "Sommer - Deckenventilator AN (Hitze)"
    trigger:
      - platform: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        above: 24
    condition:
      - condition: state
        entity_id: person.jonas_glawion
        state: "home"
      - condition: template
        value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
    action:
      - action: fan.turn_on
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          percentage: 66

  - id: summer_ceiling_fan_on_arrival
    alias: "Sommer - Deckenventilator AN (Heimkehr)"
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: "home"
    condition:
      - condition: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        above: 24
      - condition: template
        value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
    action:
      - action: fan.turn_on
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          percentage: 66

  - id: summer_ceiling_fan_off
    alias: "Sommer - Deckenventilator AUS (Kühle)"
    trigger:
      - platform: numeric_state
        entity_id: weather.no_area_forecast_zuhause
        attribute: temperature
        below: 22
    condition:
      - condition: template
        value_template: "{{ now().month in [5, 6, 7, 8, 9] }}"
    action:
      - action: fan.turn_off
        target:
          entity_id: fan.wohnzimmer_wohnzimmer_deckenventilator_u_licht
