# ============================================================================
# LIGHT AGENT - Ultra Simple Automations
# ============================================================================
# Pattern: 1 trigger, 1 condition, X devices
#
# TUYA SENSOR NOTES (ZY-M100 / WZ-M100):
# - 60-second built-in delay before detecting absence (firmware limitation)
# - May show "unavailable" intermittently - this is normal
# - Works best with direct line of sight
# - If sensor stays "on" after leaving: power cycle the sensor
# ============================================================================

# ----------------------------------------------------------------------------
# SCRIPTS
# ----------------------------------------------------------------------------
script:
  all_lights_off:
    alias: Turn Off All Lights
    mode: single
    sequence:
      - action: light.turn_off
        target:
          entity_id: all

# ----------------------------------------------------------------------------
# AUTOMATIONS - Simple format: 1 trigger, 1 condition, X devices
# ----------------------------------------------------------------------------
automation:
  # ==========================================================================
  # WOHNZIMMER (FP2 Sensor - more reliable than Tuya)
  # ==========================================================================
  - id: light_wohnzimmer_on
    alias: "Wohnzimmer Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.wohnzimmer_wohnzimmer_presence_sensor_fp2_presence_sensor_fp2_f9cf_presence_sensor_1
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id:
            - light.wohnzimmer_wohnzimmer_buffet_lichtstreifen
            - light.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          brightness_pct: 80
          color_temp_kelvin: 2700

  - id: light_wohnzimmer_off
    alias: "Wohnzimmer Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.wohnzimmer_wohnzimmer_presence_sensor_fp2_presence_sensor_fp2_f9cf_presence_sensor_1
        to: "off"
        for: "00:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id:
            - light.wohnzimmer_wohnzimmer_buffet_lichtstreifen
            - light.wohnzimmer_wohnzimmer_deckenventilator_u_licht

  # ==========================================================================
  # KÜCHE (Tuya Sensor)
  # ==========================================================================
  - id: light_kuche_on
    alias: "Küche Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.kuche_kueche_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id:
            - light.kuche_kueche_deckenlicht_1
            - light.kuche_kueche_deckenlicht_2
            - light.kuche_kueche_lichtstreifen
        data:
          brightness_pct: 100

  - id: light_kuche_off
    alias: "Küche Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.kuche_kueche_motion_sensor
        to: "off"
        for: "00:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id:
            - light.kuche_kueche_deckenlicht_1
            - light.kuche_kueche_deckenlicht_2
            - light.kuche_kueche_lichtstreifen

  # ==========================================================================
  # BADEZIMMER (Tuya Sensor)
  # ==========================================================================
  - id: light_bad_on
    alias: "Bad Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.badezimmer_badezimmer_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_badezimmer_lichtstreifen
        data:
          brightness_pct: 100

  - id: light_bad_off
    alias: "Bad Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.badezimmer_badezimmer_motion_sensor
        to: "off"
        for: "00:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_badezimmer_lichtstreifen

  # ==========================================================================
  # SCHLAFZIMMER (Tuya Sensor)
  # ==========================================================================
  - id: light_schlafzimmer_on
    alias: "Schlafzimmer Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen
        data:
          brightness_pct: 50
          color_temp_kelvin: 2700

  - id: light_schlafzimmer_off
    alias: "Schlafzimmer Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "off"
        for: "00:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen

  # ==========================================================================
  # KIFFZIMMER (Tuya Sensor)
  # ==========================================================================
  - id: light_kiffzimmer_on
    alias: "Kiffzimmer Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.kiffzimmer_kiffzimmer_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: light.kiffzimmer_kiffzimmer_lichtstreifen
        data:
          brightness_pct: 50
          color_temp_kelvin: 3000

  - id: light_kiffzimmer_off
    alias: "Kiffzimmer Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.kiffzimmer_kiffzimmer_motion_sensor
        to: "off"
        for: "00:03:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.kiffzimmer_kiffzimmer_lichtstreifen

  # ==========================================================================
  # KLEIDERSCHRANK (Aqara Door Sensor - very reliable)
  # ==========================================================================
  - id: light_kleiderschrank_on
    alias: "Kleiderschrank Licht AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.no_area_aqara_door_and_window_sensor_tuer
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_schlafzimmer_kleiderschrank_lichtstreifen

  - id: light_kleiderschrank_off
    alias: "Kleiderschrank Licht AUS"
    trigger:
      - platform: state
        entity_id: binary_sensor.no_area_aqara_door_and_window_sensor_tuer
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_schlafzimmer_kleiderschrank_lichtstreifen
