# ============================================================================
# LIGHT AGENT (Radically Simplified)
# Simple motion-based lighting.
# ============================================================================

# ----------------------------------------------------------------------------
# SCRIPTS
# ----------------------------------------------------------------------------
script:
  all_lights_off:
    alias: Turn Off All Lights
    mode: single
    sequence:
      - action: light.turn_off
        target:
          entity_id: all
        continue_on_error: true

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  # --- WOHNZIMMER ---
  - id: light_wohnzimmer_motion_on
    alias: "Wohnzimmer - Licht AN bei Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.wohnzimmer_wohnzimmer_presence_sensor_fp2_presence_sensor_fp2_f9cf_presence_sensor_1
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: numeric_state
        entity_id: sensor.wohnzimmer_wohnzimmer_presence_sensor_fp2_presence_sensor_fp2_f9cf_light_sensor_light_level
        below: 30
    action:
      - action: light.turn_on
        target:
          entity_id:
            - light.wohnzimmer_wohnzimmer_buffet_lichtstreifen
            - light.wohnzimmer_wohnzimmer_deckenventilator_u_licht
        data:
          brightness_pct: 80
          color_temp_kelvin: 2700

  - id: light_wohnzimmer_motion_off
    alias: "Wohnzimmer - Licht AUS ohne Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.wohnzimmer_wohnzimmer_presence_sensor_fp2_presence_sensor_fp2_f9cf_presence_sensor_1
        to: "off"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id:
            - light.wohnzimmer_wohnzimmer_buffet_lichtstreifen
            - light.wohnzimmer_wohnzimmer_deckenventilator_u_licht

  # --- KÜCHE ---
  - id: light_kuche_motion_on
    alias: "Küche - Licht AN bei Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.kuche_kueche_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: sun
        after: sunset
        before: sunrise
    action:
      - action: light.turn_on
        target:
          entity_id:
            - light.kuche_kueche_deckenlicht_1
            - light.kuche_kueche_deckenlicht_2
            - light.kuche_kueche_lichtstreifen
        data:
          brightness_pct: 100

  - id: light_kuche_motion_off
    alias: "Küche - Licht AUS ohne Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.kuche_kueche_motion_sensor
        to: "off"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id:
            - light.kuche_kueche_deckenlicht_1
            - light.kuche_kueche_deckenlicht_2
            - light.kuche_kueche_lichtstreifen

  # --- BAD ---
  - id: light_bad_motion_on
    alias: "Bad - Licht AN bei Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.badezimmer_badezimmer_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: sun
        after: sunset
        before: sunrise
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_badezimmer_lichtstreifen
        data:
          brightness_pct: 100

  - id: light_bad_motion_off
    alias: "Bad - Licht AUS ohne Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.badezimmer_badezimmer_motion_sensor
        to: "off"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_badezimmer_lichtstreifen

  # --- SCHLAFZIMMER ---
  - id: light_schlafzimmer_motion_on
    alias: "Schlafzimmer - Licht AN bei Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: sun
        after: sunset
        before: sunrise
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen
        data:
          brightness_pct: 50
          color_temp_kelvin: 2700

  - id: light_schlafzimmer_motion_off
    alias: "Schlafzimmer - Licht AUS ohne Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "off"
        for: "00:01:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen

  # --- KIFFZIMMER ---
  - id: light_kiffzimmer_motion_on
    alias: "Kiffzimmer - Licht AN bei Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.kiffzimmer_kiffzimmer_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: sun
        after: sunset
        before: sunrise
    action:
      - action: light.turn_on
        target:
          entity_id: light.kiffzimmer_kiffzimmer_lichtstreifen
        data:
          brightness_pct: 50
          color_temp_kelvin: 3000

  - id: light_kiffzimmer_motion_off
    alias: "Kiffzimmer - Licht AUS ohne Bewegung"
    trigger:
      - platform: state
        entity_id: binary_sensor.kiffzimmer_kiffzimmer_motion_sensor
        to: "off"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.kiffzimmer_kiffzimmer_lichtstreifen

  # --- UTILITY ---
  - id: wardrobe_light_auto
    alias: "Kleiderschrank - Licht AN bei Türöffnung"
    trigger:
      - platform: state
        entity_id: binary_sensor.no_area_aqara_door_and_window_sensor_tuer
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_schlafzimmer_kleiderschrank_lichtstreifen

  - id: wardrobe_light_off
    alias: "Kleiderschrank - Licht AUS bei Türschließung"
    trigger:
      - platform: state
        entity_id: binary_sensor.no_area_aqara_door_and_window_sensor_tuer
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_schlafzimmer_kleiderschrank_lichtstreifen

  - id: night_bathroom_low_light
    alias: "Nacht - Dimmbeleuchtung Bad"
    trigger:
      - platform: state
        entity_id: binary_sensor.badezimmer_badezimmer_motion_sensor
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: time
        after: "22:00:00"
        before: "07:00:00"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_badezimmer_lichtstreifen
        data:
          brightness_pct: 10
          color_temp_kelvin: 2200

  - id: night_hallway_guide_light_on
    alias: "Nacht - Orientierungslicht Flur AN"
    trigger:
      - platform: state
        entity_id: binary_sensor.schlafzimmer_schlafzimmer_presence_sensor_bewegung
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: time
        after: "22:00:00"
        before: "07:00:00"
    action:
      - action: light.turn_on
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen
        data:
          brightness_pct: 5
          color_temp_kelvin: 2200

  - id: night_hallway_guide_light_off
    alias: "Nacht - Orientierungslicht Flur AUS"
    trigger:
      - platform: state
        entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen
        to: "on"
        for: "00:02:00"
    condition:
      - condition: state
        entity_id: input_boolean.auto_lights_enabled
        state: "on"
      - condition: time
        after: "22:00:00"
        before: "07:00:00"
    action:
      - action: light.turn_off
        target:
          entity_id: light.schlafzimmer_schlafzimmer_bett_lichtstreifen
