# ============================================================================
# PLANT GROWING AGENT (Radically Simplified)
# Strain: Strawberry Lemonade (Barney's Farm)
# ============================================================================

# ----------------------------------------------------------------------------
# HELPERS
# ----------------------------------------------------------------------------
input_select:
  cannabis_stage:
    name: "Cannabis Growth Stage"
    options:
      - "Off"
      - "Germination"
      - "Seedling"
      - "Vegetative"
      - "Early Flower"
      - "Late Flower"
      - "Drying"
    initial: "Off"
    icon: mdi:leaf

# ----------------------------------------------------------------------------
# SENSORS (Targets & Averages)
# ----------------------------------------------------------------------------
template:
  - sensor:
      - name: "Cannabis Target Temp High"
        unique_id: cannabis_target_temp_high
        unit_of_measurement: "°C"
        state: >
          {% set stage = states('input_select.cannabis_stage') %}
          {% if stage == 'Germination' %} 26
          {% elif stage == 'Seedling' %} 25
          {% elif stage == 'Vegetative' %} 28
          {% elif stage == 'Early Flower' %} 26
          {% elif stage == 'Late Flower' %} 24
          {% else %} 25
          {% endif %}

      - name: "Cannabis Target Temp Low"
        unique_id: cannabis_target_temp_low
        unit_of_measurement: "°C"
        state: >
          {% set stage = states('input_select.cannabis_stage') %}
          {% if stage == 'Germination' %} 24
          {% elif stage == 'Seedling' %} 22
          {% elif stage == 'Vegetative' %} 21
          {% elif stage == 'Early Flower' %} 20
          {% elif stage == 'Late Flower' %} 18
          {% else %} 20
          {% endif %}

      - name: "Cannabis Target Humidity High"
        unique_id: cannabis_target_humidity_high
        unit_of_measurement: "%"
        state: >
          {% set stage = states('input_select.cannabis_stage') %}
          {% if stage == 'Germination' %} 80
          {% elif stage == 'Seedling' %} 70
          {% elif stage == 'Vegetative' %} 65
          {% elif stage == 'Early Flower' %} 55
          {% elif stage == 'Late Flower' %} 45
          {% else %} 60
          {% endif %}

      - name: "Cannabis Target Humidity Low"
        unique_id: cannabis_target_humidity_low
        unit_of_measurement: "%"
        state: >
          {% set stage = states('input_select.cannabis_stage') %}
          {% if stage == 'Germination' %} 70
          {% elif stage == 'Seedling' %} 65
          {% elif stage == 'Vegetative' %} 55
          {% elif stage == 'Early Flower' %} 50
          {% elif stage == 'Late Flower' %} 40
          {% else %} 45
          {% endif %}

      - name: "Cannabis Average Soil Moisture"
        unique_id: cannabis_average_soil_moisture
        unit_of_measurement: "%"
        state: >
          {{ ( (states('sensor.permanent_marker_l_cannabis_soil_moisture') | float(0)) + 
               (states('sensor.cap_junky_m_cannabis_soil_moisture') | float(0)) + 
               (states('sensor.candy_store_r_cannabis_soil_moisture') | float(0)) ) / 3 | round(1) }}

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  # --- FAN CONTROL ---
  - id: cannabis_fan_on_high_humidity
    alias: "Kiffzimmer - Filter AN (Feuchtigkeit hoch)"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_luftfeuchtigkeit') | float(0) > states('sensor.cannabis_target_humidity_high') | float(0) }}"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.cannabis_stage
            state: "Off"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_aktivkohlefilter_steckdose_zelt

  - id: cannabis_fan_on_high_temp
    alias: "Kiffzimmer - Filter AN (Temperatur hoch)"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') | float(0) > states('sensor.cannabis_target_temp_high') | float(0) }}"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.cannabis_stage
            state: "Off"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_aktivkohlefilter_steckdose_zelt

  - id: cannabis_fan_off_optimal
    alias: "Kiffzimmer - Filter AUS (Optimal)"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_luftfeuchtigkeit') | float(0) < states('sensor.cannabis_target_humidity_low') | float(0) }}"
    condition:
      - condition: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') | float(0) < states('sensor.cannabis_target_temp_high') | float(0) - 2 }}"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_aktivkohlefilter_steckdose_zelt

  # --- HEATER CONTROL ---
  - id: cannabis_heater_on_cold
    alias: "Kiffzimmer - Heizung AN (Zu kalt)"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') | float(0) < states('sensor.cannabis_target_temp_low') | float(0) }}"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.cannabis_stage
            state: "Off"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1

  - id: cannabis_heater_off_target
    alias: "Kiffzimmer - Heizung AUS (Ziel erreicht)"
    trigger:
      - platform: template
        value_template: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') | float(0) > states('sensor.cannabis_target_temp_low') | float(0) + 1 }}"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1

  - id: cannabis_tent_heater_safety
    alias: "Kiffzimmer - Heizung NOT-AUS (5 min)"
    trigger:
      - platform: state
        entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1
        to: "on"
        for:
          minutes: 5
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1

  # --- LIGHT CYCLE ---
  - id: cannabis_light_on_morning
    alias: "Kiffzimmer - Licht AN (06:00)"
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.cannabis_stage
            state: ["Off", "Drying"]
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1_2

  - id: cannabis_light_off_flower
    alias: "Kiffzimmer - Licht AUS Blüte (18:00)"
    trigger:
      - platform: time
        at: "18:00:00"
    condition:
      - condition: state
        entity_id: input_select.cannabis_stage
        state: ["Early Flower", "Late Flower"]
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1_2

  - id: cannabis_light_off_veg
    alias: "Kiffzimmer - Licht AUS Veg (00:00)"
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      - condition: state
        entity_id: input_select.cannabis_stage
        state: ["Germination", "Seedling", "Vegetative"]
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.kiffzimmer_kiffzimmer_cannabis_zelt_heizluefter_schalter_1_2

  # --- AI BRAIN ---
  - id: ai_grow_bot_check
    alias: "AI - Grow Bot Check (Hourly)"
    trigger:
      - platform: time_pattern
        hours: "/1"
    action:
      - action: rest_command.n8n_grow_bot_check
        data:
          temperature: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') }}"
          humidity: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_luftfeuchtigkeit') }}"
          stage: "{{ states('input_select.cannabis_stage') }}"
          timestamp: "{{ now().isoformat() }}"

  - id: ai_grow_bot_daily
    alias: "AI - Grow Bot Daily Log (08:00)"
    trigger:
      - platform: time
        at: "08:00:00"
    action:
      - action: rest_command.n8n_grow_bot_check
        data:
          temperature: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_temperatur') }}"
          humidity: "{{ states('sensor.kiffzimmer_kiffzimmer_zelt_humidity_sensor_luftfeuchtigkeit') }}"
          stage: "{{ states('input_select.cannabis_stage') }}"
          timestamp: "{{ now().isoformat() }}"
          report_type: "daily_summary"
