# ============================================================================
# SYSTEM AGENT (Radically Simplified)
# System-wide logic and maintenance.
# ============================================================================

# ----------------------------------------------------------------------------
# AUTOMATIONS
# ----------------------------------------------------------------------------
automation:
  - alias: "System - Startup Notification"
    trigger:
      - platform: homeassistant
        event: start
    action:
      - action: notify.alle_geraete
        data:
          title: "System Started"
          message: "Home Assistant has successfully restarted."

  - alias: "Putzfrau - Einzug erkannt"
    trigger:
      - platform: state
        entity_id: binary_sensor.no_area_aqara_door_and_window_sensor_tuer
        to: "on"
    condition:
      - condition: time
        weekday: [wed, thu, fri]
        after: "08:00:00"
        before: "15:00:00"
      - condition: state
        entity_id: person.jonas_glawion
        state: "not_home"
    action:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.cleaning_mode
      - action: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.auto_lights_enabled
            - input_boolean.auto_shutters_enabled

  # --- CLEANING MODE ON ---
  - alias: "Reinigungsmodus - Blinds Open"
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_mode
        to: "on"
    action:
      - action: cover.open_cover
        target:
          entity_id: all

  - alias: "Reinigungsmodus - Lights On"
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_mode
        to: "on"
    action:
      - action: light.turn_on
        target:
          entity_id: all
        data:
          brightness_pct: 100
          color_temp_kelvin: 6500

  - alias: "Reinigungsmodus - Notify On"
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_mode
        to: "on"
    action:
      - action: notify.alle_geraete
        data:
          title: "🧹 Reinigung gestartet"
          message: "Putzfrau ist eingetroffen. Modus AKTIVIERT."

  # --- CLEANING MODE OFF ---
  - alias: "Reinigungsmodus - Lights Off"
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_mode
        to: "off"
    action:
      - action: light.turn_off
        target:
          entity_id: all

  - alias: "Reinigungsmodus - Notify Off"
    trigger:
      - platform: state
        entity_id: input_boolean.cleaning_mode
        to: "off"
    action:
      - action: notify.alle_geraete
        data:
          title: "🧹 Reinigung beendet"
          message: "Reinigung beendet. Willkommen zurück!"
      - action: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.auto_lights_enabled
            - input_boolean.auto_shutters_enabled

  - alias: "Reinigungsmodus - Auto Aus bei Ankunft"
    trigger:
      - platform: state
        entity_id: person.jonas_glawion
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.cleaning_mode
        state: "on"
    action:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.cleaning_mode

  # --- HEATING SEASON ---
