automation:
  - id: fix_tplink_presets
    alias: "System - Fix TP-Link Presets"
    description: "Forces a valid preset when TP-Link devices default to 'Not set'"
    mode: queued
    trigger:
      - platform: state
        entity_id:
          - select.wohnzimmer_wohnzimmer_buffet_lichtstreifen_lichtvoreinstellung
          - select.kuche_kueche_deckenlicht_2_lichtvoreinstellung
          - select.kuche_kueche_deckenlicht_1_lichtvoreinstellung
          - select.kuche_kueche_lichtstreifen_lichtvoreinstellung
          - select.schlafzimmer_schlafzimmer_kleiderschrank_lichtstreifen_lichtvoreinstellung
          - select.schlafzimmer_badezimmer_lichtstreifen_lichtvoreinstellung
          - select.schlafzimmer_schlafzimmer_bett_lichtstreifen_lichtvoreinstellung
          - select.kiffzimmer_kiffzimmer_lichtstreifen_lichtvoreinstellung
        to: "Not set"
    action:
      - action: select.select_option
        target:
          entity_id: "{{ trigger.entity_id }}"
        data:
          option: "Light preset 1"
      - action: notify.mobile_app_redmi_note_12_pro_5g
        data:
          message: "Fixed preset for {{ state_attr(trigger.entity_id, 'friendly_name') }}"
